# Similar photosynthetic trait adaptation to low light has been shown for
# Physocarpus cultivars (Zhang et al. 2016) and sweet pepper (Sui et al. 2012), more().
# Moreover, increases in chlorophyll content in shade have been detected across ecosystems,
# Chlorophyll greater in shade leaves for mahogany seedlings (Goncalves et al. 2001


Photosynthetic nitrogen use efficiency differed by 56% among Selaginella species 
(p < 0.001, F=9.21) and was broadly lower in swamp habitat types (p= 0.017, F=4.62). 
No effect of species or habitat type was detected with photosynthetic phosphorus use efficiency.



###discussion

EXTRA text

A major focus of plant ecology is understanding how and why communities assemble the way they do. Current research suggest assembly rules are quite complex and communities can be structured along a combination of stochastic, phylogenetic and functional means. These assembly rules are likely to be increasingly complex in species diverse tropical forests. This study uniquely investigated whether functional traits mediate species distribution of an early lineage of vascular plants into different niches on wet tropical forest floors. We then explored how the in situ ecophysiology of these understudied Selaginella taxa compare to co-occurring terrestrial understory ferns. 

Community assembly processes shape the distribution of functional trait values within communities by habitat filter restrictions and microsite partitioning, which limits similarity
of coexisting species (Cornwell & Ackerly 2009). Habitat filtering has been shown to influence tropical species distribution patterns and to shift intraspecific trait values for palms (Anderson et al. 2011), dry forest communities (Lebrija-Trejos et al. 2010), cloud forest tree communities (Long et al. 2011) and mature forests (Shipley et al. 2012) across gradients in soil nutrient availability, light, temperature and rainfall. Selaginella species have been previously shown to exhibit high family importance values in tropical forest understories (Lu et al. 2011). Consequently, distribution patterns of Selaginella taxa likely contribute to tropical understory structure and function. To begin to build a foundation for the understanding of community assembly in lycophytes, we must first understand some of the most basic aspects of their ecophysiology. Only then can we explore whether convergent traits emerge among the various observed understory habitats that lycophyte taxa inhabit (Table 1).

Few studies have explored in-situ leaf-level gas exchange of early lineage Lycopsids (see Zeir et al 2015).  Here, we show a greater than two-fold range in An across seven Selaginella species in their natural habitats. Measured rates of An fit within previously reported max photosynthetic rates (1.6 - 6.15 μmols m-2 s-1) of two Selaginella species (Brodribb et al. 2007; Brodribb et al. 2009). Rates of gs (~0.08 mols m-2 s-1) were low, but also similar to reported rates (0.06 - 0.19 mols m-2 s-1) of Selaginella species (Brodribb et al. 2009; Ruszala et al. 2011). Surprisingly, differences in leaf-level physiology were not detected between habitat types, despite large species-level differences in An, gs and ITE. Consequently, species associations with physiological traits (see Figure 2) were likely not driven by habitat, or at least not by the microclimate variables used to define habitat in this study. 

Alternatively, functional convergence of leaf stoichiometric, anatomical and photosynthetic traits was detected between habitat types with Selaginella taxa. Increased stomatal density was detected in taxa occupying open-canopy habitats. Whether early lineage lycophytes exhibit predominantly active or passive stomatal control mechanisms is still being debated (Brodribb & McAdamm 2011; Ruszala et al., 2011; McAdam and Brodribb 2012), but Selaginella taxa are shown to be particularly sensitive to increases in VPD (Table 2, McAdam and Brodribb 2013). Interestingly, increases in the density of small-sized stomata (see Figure 3) likely represent a mechanism for Selaginella taxa to overcome inefficient stomatal responses to higher vapor pressure deficits in these open canopy habitats. Small and more dense stomata may have faster response times than larger stomata (Drake et al. 2012), allowing Selaginella taxa in high-light habitats to better maintain plant water balance.
The exact nature of this strategy is unknown, but warrants further study to elucidate how Selaginella taxa maintain plant water balance in diverse microclimates.

An established suite of plant functional traits allows species to segregate into light limiting environments (Valladeres and Niinemets 2008), which may be pronounced in tropical rainforests where light profoundly limits growth (Whitmore 1996). Here, foliar N content of Selaginella taxa was higher in both closed canopy habitats compared to full sun habitats. Shifts in foliar N may be a simple consequence of microsite conditions, as low soil N has been detected in disturbed high light tropical gaps (Bungard et al. 2000). Alternatively, increased N investment into photosynthetic machinery in low-light habitats is a likely mechanism to improve light capture (Hikosaka & Terashime 1995; Poorter & Evans 1998). Selaginella taxa in swamp habitats were also characterized by higher foliar chlorophyll content and a lower LCP. In forest understory plants, increases in chlorophyll content typically include greater investment in Chl b to increase absorption of blue light (Li et al. 2018). Additionally, a low LCP in shade adapted species allows for greater net carbon balance at low light (Craine & Reich 2005). Here, convergent trait responses related to photosynthetic light capture have likely increased the growth potential of specific Selaginella taxa in low light habitats of this tropical understory.

Community assembly processes shape the distribution of functional trait values within communities by habitat filter restrictions and microsite partitioning, which limits similarity
of coexisting species (Cornwell & Ackerly 2009). 

Trait selection can occur across strategies within habitats, leading to ecological sorting of species distributions (Reich et al. 2003;_
                                                                                                                     
                                                                                                                     Neither An nor gs were correlated with either stomatal length or stomatal density (Figure 4C) across surveyed Selaginella species. Alternatively, gs was weakly positively correlated to stomatal density (p = 0.05, r2 = 0.13, Figure 4D) and negatively correlated to stomatal length (p < 0.001, r2 = 0.45) across fern species. No relationship with An and stomatal traits was detected across fern species.
                                                                                                                     